proc help {} {
	puts "Commands:"
	puts "################"
	puts "read_file <string>"
	puts "		reads input data from file"
	puts ""
	puts "write_file <string>"
	puts "		writes out data to file"
	puts ""
	puts "execute_script <string>"
	puts "		runs set of commands from file"
	puts ""
	puts "display_object \[-below <string\[/string\]>\]"
	puts "		shows all objects or subset under hierachy"
	puts ""
	puts "delete_object <string> \[-below <string\[/string\]>\]"
	puts "		removes top level object or objects under hierarchy"
	puts ""
	puts "add_object <string> \[-below <string\[/string\]>\]"
	puts "		adds object on top level or under hierarchy"
	puts ""
	puts "exit"
	puts "		exits the tool"
	puts ""
}
